[package]
name = "vec845"
version = "1.1.0"
description = "845-VEC relay test-value calculator"
authors = ["Eric Kiechler"]
edition = "2021"
rust-version = "1.77"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true
