#!/usr/bin/env node
/* Download the three families as woff2 (latin subset) and emit src/fonts.css
   with every face inlined as a data URI.

   The tool is used in substations with no signal. Linking Google Fonts means
   the product looks different offline than it did when the customer bought it,
   which is a support call on a paid tool. Bundling costs a few hundred KB and
   removes the variable entirely — and removes a third-party request from a
   product going into enterprise environments. */
import fs from 'node:fs';

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';
const FAMILIES = [
  ['Barlow+Condensed', 'Barlow Condensed', [500, 600, 700]],
  ['IBM+Plex+Sans',    'IBM Plex Sans',    [400, 500, 600]],
  ['IBM+Plex+Mono',    'IBM Plex Mono',    [400, 500, 600]]
];

const get = async (url, bin) => {
  const r = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!r.ok) throw new Error(`${r.status} ${url}`);
  return bin ? Buffer.from(await r.arrayBuffer()) : r.text();
};

let out = `/* Fonts bundled at build time so the tool renders identically offline.
   Barlow Condensed and IBM Plex are used under the SIL Open Font Licence 1.1.
   Latin subset only. Generated by tools/fetch-fonts.mjs — do not hand-edit. */\n`;
let total = 0, faces = 0;

for (const [q, name, weights] of FAMILIES) {
  const css = await get(`https://fonts.googleapis.com/css2?family=${q}:wght@${weights.join(';')}&display=swap`);
  /* Keep only the latin block — the others are for scripts this tool never shows. */
  const blocks = css.split('@font-face').slice(1)
    .map(b => '@font-face' + b)
    .filter(b => /unicode-range:[^;]*U\+0000-00FF/.test(b));
  for (const b of blocks) {
    const w = (b.match(/font-weight:\s*(\d+)/) || [])[1];
    const url = (b.match(/url\((https:[^)]+\.woff2)\)/) || [])[1];
    const ur = (b.match(/unicode-range:\s*([^;]+);/) || [])[1];
    if (!w || !url) continue;
    const buf = await get(url, true);
    total += buf.length; faces++;
    out += `@font-face{font-family:'${name}';font-style:normal;font-weight:${w};font-display:swap;` +
           `src:url(data:font/woff2;base64,${buf.toString('base64')}) format('woff2');` +
           (ur ? `unicode-range:${ur.trim()};` : '') + `}\n`;
  }
  console.log(`  ${name}: ${blocks.length} face(s)`);
}
fs.writeFileSync('src/fonts.css', out);
console.log(`\n${faces} faces, ${(total / 1024).toFixed(0)} KB of woff2 -> src/fonts.css (${(out.length / 1024).toFixed(0)} KB)`);
